# Generated by Django 3.2.12 on 2023-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
