# Generated by Django 3.2.12 on 2023-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20230403_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
