# Generated by Django 3.2.12 on 2023-03-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20230306_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(to='repository.Author'),
        ),
    ]
