# Generated by Django 3.2.12 on 2023-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_post_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(default='', to='repository.Author'),
        ),
    ]
