# Generated by Django 3.2.12 on 2023-04-03 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "repository",
            "0004_remove_post_title",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Paper",
        ),
    ]
