# Generated by Django 3.2.12 on 2023-04-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_announcement_dataset_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='timestamp',
        ),
    ]
