# Generated by Django 3.2.12 on 2023-04-05 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "repository",
            "0009_auto_20230405_1029",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Paper",
            new_name="Publication",
        ),
    ]
