# Generated by Django 3.2.12 on 2023-04-05 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "repository",
            "0011_publication_type",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conference",
            name="link",
        ),
    ]
