# Generated by Django 3.2.12 on 2023-04-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20230405_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.conference'),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('WORKSHOP', 'Workshop'), ('TUTORIAL', 'Tutorial')], default='Tutorial', max_length=100),
        ),
    ]
