# Generated by Django 3.2.12 on 2023-06-20 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "repository",
            "0014_auto_20230405_1339",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
