# Generated by Django 3.2.12 on 2023-09-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_delete_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='user_name',
        ),
    ]
