# Generated by Django 3.2.12 on 2023-06-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdt_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='tldr',
            field=models.TextField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
