# Generated by Django 3.2.12 on 2023-06-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cdt_newsletter", "0003_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "announcement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cdt_newsletter.announcement",
                    ),
                ),
                ("date", models.DateField()),
            ],
            bases=(
                "cdt_newsletter.announcement",
            ),
        ),
    ]
