# Generated by Django 3.2.12 on 2023-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdt_newsletter", "0005_announcement_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="publication_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
