# Generated by Django 3.2.12 on 2023-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cdt_newsletter", "0006_alter_announcement_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
