# Generated by Django 3.2.12 on 2023-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230404_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='resource_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
